version: '3.8'

services:
  roach:
    image: cockroachdb/cockroach:latest-v20.1
    container_name: roach
    hostname: db
    networks:
      - mynet
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - roach:/cockroach/cockroach-data
    command: start-single-node --insecure

  docker-gs-ping-roach:
    depends_on: 
      - roach
    build:
      context: .
    container_name: rest-server
    hostname: rest-server
    networks:
      - mynet
    ports:
      - 80:8080

    env_file:
      - ./.env

    environment:
      - PGDATABASE=${PGDATABASE}
      - PGHOST=db
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}

volumes:
  roach:

networks:
  mynet:
    driver: bridge
